[build-system]
requires = [ "setuptools >= 70.1.1",]
build-backend = "setuptools.build_meta"

[project]
name = "your_plugin"
version = "0.0.0"
readme = "README.md"
description = "HERMES plugin for your_source"
keywords = [ "publishing", "metadata", "automation",]
requires-python = ">= 3.10"
classifiers = [ "Development Status :: 1 - Planning", "Environment :: Plugins", "Programming Language :: Python :: 3",]
dependencies = [ "hermes>=0.9.0",]
authors = [
    {name = "your_name", email = "your@email.address"}
]
license = "Apache-2.0"

[project.optional-dependencies]
dev = [ "pytest>=8.2.2", "pytest-cov>=3.0.0", "taskipy>=1.10.3", "flake8>=5.0.4", "reuse>=1.1.2",]

[project.urls]
Repository = "link_to_your_repository"

[tool.setuptools]
packages = [ "your_plugin",]

[tool.setuptools.package-dir]
"" = "src"
