name: Publish plugin to the HERMES Marketplace

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    name: Create "Add plugin to marketplace" issue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Create "Add plugin to marketplace" issue
        run: gh issue --repo ${{ github.repository }} create --title "$TITLE" --body "$BODY"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: Add plugin to marketplace
          BODY: |
            Thank you for building a plugin for `hermes`. We encourage you to share it with the community!

            The [HERMES plugin marketplace](https://hermes.software-metadata.pub/#plugins) is a curated list of plugins on our website that allows you to share plugins that you developed, and others to find them.

            You can send us the required information to add your plugin to the marketplace, by [creating an issue in the `hermes` repository](https://github.com/softwarepub/hermes/issues/new?template=add-plugin-to-marketplace.yml).
  delete_workflow:
    name: Delete this run-once workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete this run-once workflow
        run: gh workflow --repo ${{ github.repository }} disable "Publish plugin to the HERMES Marketplace"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}